//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademiPlus_Transportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Product()
        {
            this.TBL_Transportation = new HashSet<TBL_Transportation>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductSizeType { get; set; }
        public string ProductSize { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Transportation> TBL_Transportation { get; set; }
        public virtual TBL_Category TBL_Category { get; set; }
    }
}
